name: 'Az destroyer of resources'
description: 'Az destroyer of resources'
inputs:
  resourceGroupName:  # id of input
    description: 'Id of resource to delete'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'